variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - tata

.machine: &runner-shell
    tags: 
        - vitamui, shell

test_tata:
  stage: tata
  only:
    - main
  <<: *runner-shell
  script:
    # La commande "git remote add" est utilisée pour créer un dépôt distant. Le premier argument est le nom du dépôt distant et le deuxième son URL
    - git remote add origin https://$TOKEN:x-oauth-basic@$LIEN_CIBLE
    # on se place dans la branche du dépôt distant
    - git checkout -b $BRANCHE_CIBLE
    # on met à jour la branche distante (Logiquement, elle devrait toujours être au même niveau que la master local)
    - git pull origin $BRANCHE_CIBLE
    # on push sur github sur la branche choisie 
    - git push --set-upstream origin $BRANCHE_CIBLE
