variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

stages:
  - build_vitamui
  # - start_mongo
  # - build_services
  # - deploy_services

.machine: &runner-dev
    tags:
        - vitamui, docker

# .machine: &runner-shell
#     tags:
#         - pastis, shell
build_project:dev:
  image: maven:3.6.3-jdk-11
  stage: build_vitamui
  only:
    - feat/test-integration
  <<: *runner-dev
  script:
    - mvn clean install -DskipTests
  dependencies: []

# start_mongo:dev:
#   stage: start_mongo
#   only:
#     - feat/test-integration
#   <<: *runner-shell
#   script:
#     - sh tools/docker/mongo/restart_dev.sh

# build_services:dev:
#   stage: build_services
#   only:
#     - feat/test-integration
#   <<: *runner-shell
#   script:
#     - docker build -f Dockerfile .


# deploy_services:dev:
#   stage: deploy_services
#   only:
#     - feat/test-integration
#   <<: *runner-shell
#   script:
#     - use docker compose to expose services
