variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

stages:
  - build_vitamui
#  - start_mongo
#  - create_network
  - deploy_services

.machine: &runner-dev
    tags:
        - vitamui, docker

.machine: &runner-shell
    tags:
        - vitamui, shell
build_project:dev:
  stage: build_vitamui
  only:
    - feat/test-integration
  <<: *runner-shell
  script:
    - docker build --cache-from none -f Dockerfile .
  dependencies: []

#start_mongo:dev:
#  stage: start_mongo
#  only:
#    - feat/test-integration
#  <<: *runner-shell
#  script:
#    - cd tools/docker/mongo/
#    - sh restart_dev.sh

#create_network:dev:
#  stage: create_network
#  only:
#    - feat/test-integration
#  <<: *runner-shell
#  script:
#    - docker network create vitamui
#    - docker network connect vitamui vitamui-mongo
deploy_services:dev:
  stage: deploy_services
  only:
    - feat/test-integration
  <<: *runner-shell
  script:
    #- use docker compose to expose services
    - sh tag-images.sh
    - sh run-images.sh
