docker run -d --network host --name security-internal -p "8084:8084" cines/vitamui-security-internal
docker run -d --network host --name iam-internal -p "7083:7083" cines/vitamui-iam-internal
docker run -d --network host --name iam-external -p "8083:8083" cines/vitamui-iam-external
docker run -d --network host --name cas-server -p "8080:8080" cines/vitamui-cas
docker run -d --network host --name ui-portal -p "9000:9000" cines/vitamui-ui-portal
docker run -d --network host --name ui-identity -p "9001:9001" cines/vitamui-ui-identity
docker run -d --network host --name ui-pastis -p "8051:8051" cines/vitamui-ui-pastis
docker run -d --network host --name front-pastis -p "4251:80" cines/vitamui-front-pastis
docker run -d --network host --name front-identity -p "4201:80" cines/vitamui-front-identity
docker run -d --network host --name front-portal -p "4200:80" cines/vitamui-front-portal
