docker rmi $(docker images --filter label=name=dependencies --format {{.ID}}) || echo 'image not found'
docker rmi $(docker images --filter label=name=build-services --format {{.ID}}) || echo 'image not found'
#docker rmi $(docker images --filter label=name=build-front --format {{.ID}}) || echo 'image not found'
docker tag $(docker images --filter label=name=security-internal --format {{.ID}}) cines/vitamui-security-internal || echo 'image not found'
docker tag $(docker images --filter label=name=iam-internal --format {{.ID}}) cines/vitamui-iam-internal || echo 'image not found'
docker tag $(docker images --filter label=name=iam-external --format {{.ID}}) cines/vitamui-iam-external || echo 'image not found'
docker tag $(docker images --filter label=name=cas-server --format {{.ID}}) cines/vitamui-cas || echo 'image not found'
docker tag $(docker images --filter label=name=ui-identity --format {{.ID}}) cines/vitamui-ui-identity || echo 'image not found'
docker tag $(docker images --filter label=name=ui-portal --format {{.ID}}) cines/vitamui-ui-portal || echo 'image not found'
docker tag $(docker images --filter label=name=ui-pastis --format {{.ID}}) cines/vitamui-ui-pastis || echo 'image not found'
docker tag $(docker images --filter label=name=portal-front --format {{.ID}}) cines/vitamui-front-portal || echo 'image not found'
docker tag $(docker images --filter label=name=pastis-front --format {{.ID}}) cines/vitamui-front-pastis || echo 'image not found'
docker tag $(docker images --filter label=name=identity-front --format {{.ID}}) cines/vitamui-front-identity || echo 'image not found'

