server:
  host: sandbox23-adm.cines.fr
  port: 8051
  scheme: https
  ssl:
    key-store: ui/ui-pastis/src/main/config/ui-pastis.jks
    key-store-password: jkspasswd
    key-password: jkspasswd


logging:
    level:
        fr.gouv.vitamui: DEBUG
        org.springframework.web: INFO

management.endpoints.web.exposure.include: "*"
# Uncomment if you want to use you specific logback config.
#logging:
config: ui/ui-pastis/src/main/config/logback.xml
cors.allowed-origins: https://sandbox23-adm.cines.fr:4251, https://localhost
